services:
  backend:
    # ... existing backend configuration ...
    # Add these lines:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000  # Keep your default command
    # Add aliases for common operations
    profiles:
      - app
    
  # Add a new service for CLI operations
  backend-cli:
    extends: backend
    profiles:
      - cli
    command: python -m app.config_cli
    entrypoint: [] 