services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - UVICORN_RELOAD=true
    volumes:
      - ./backend/app:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
