services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - UVICORN_RELOAD=false
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backend/app:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - VITE_PUBLIC_API_URL=${VITE_PUBLIC_API_URL}
      - TEST_VARIABLE=${TEST_VARIABLE}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max-connections=1000
      --innodb-buffer-pool-size=1G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

volumes:
  mysql_data:
