from fastapi import APIRouter
from typing import List
import logging
from ..config import settings

router = APIRouter()

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

ENVIRONMENT = settings.ENVIRONMENT

base_api_url = "/"
if ENVIRONMENT == "development":
    base_api_url = "/api/"
    
@router.get(base_api_url + "locations")
async def get_locations():
    """Return a list of available locations"""
    
    return [
        {'id': 'GM1680', 'name': 'Aa en Hunze', 'type': 'municipality'},
        {'id': 'GM0482', 'name': 'Alblasserdam', 'type': 'municipality'},
        {'id': 'GM0358', 'name': 'Aalsmeer', 'type': 'municipality'},
        {'id': 'GM0197', 'name': 'Aalten', 'type': 'municipality'},
        {'id': 'GM0613', 'name': 'Albrandswaard', 'type': 'municipality'},
        {'id': 'GM0141', 'name': 'Almelo', 'type': 'municipality'},
        {'id': 'GM0034', 'name': 'Almere', 'type': 'municipality'},
        {'id': 'GM0484', 'name': 'Alphen aan den Rijn', 'type': 'municipality'},
        {'id': 'GM1723', 'name': 'Alphen-Chaam', 'type': 'municipality'},
        {'id': 'GM0307', 'name': 'Amersfoort', 'type': 'municipality'},
        {'id': 'GM0060', 'name': 'Ameland', 'type': 'municipality'},
        {'id': 'GM0361', 'name': 'Alkmaar', 'type': 'municipality'},
        {'id': 'GM0362', 'name': 'Amstelveen', 'type': 'municipality'},
        {'id': 'GM0363', 'name': 'Amsterdam', 'type': 'municipality'},
        {'id': 'GM0363S56', 'name': 'Amsterdam Stadsdeel Centrum', 'type': 'municipality'},
        {'id': 'GM0363S90', 'name': 'Amsterdam Stadsdeel Nieuw-West', 'type': 'municipality'},
        {'id': 'GM0363S10', 'name': 'Amsterdam Stadsdeel Noord', 'type': 'municipality'},
        {'id': 'GM0363S88', 'name': 'Amsterdam Stadsdeel Oost', 'type': 'municipality'},
        {'id': 'GM0363S91', 'name': 'Amsterdam Stadsdeel West', 'type': 'municipality'},
        {'id': 'GM0363S89', 'name': 'Amsterdam Stadsdeel Zuid', 'type': 'municipality'},
        {'id': 'GM0363S17', 'name': 'Amsterdam Stadsdeel Zuidoost', 'type': 'municipality'},
        {'id': 'GM1959', 'name': 'Altena', 'type': 'municipality'},
        {'id': 'GM0202', 'name': 'Arnhem', 'type': 'municipality'},
        {'id': 'GM0106', 'name': 'Assen', 'type': 'municipality'},
        {'id': 'GM0743', 'name': 'Asten', 'type': 'municipality'},
        {'id': 'GM0744', 'name': 'Baarle-Nassau', 'type': 'municipality'},
        {'id': 'GM0308', 'name': 'Baarn', 'type': 'municipality'},
        {'id': 'GM0489', 'name': 'Barendrecht', 'type': 'municipality'},
        {'id': 'GM0203', 'name': 'Barneveld', 'type': 'municipality'},
        {'id': 'GM1954', 'name': 'Beekdaelen', 'type': 'municipality'},
        {'id': 'GM0888', 'name': 'Beek', 'type': 'municipality'},
        {'id': 'GM0889', 'name': 'Beesel', 'type': 'municipality'},
        {'id': 'GM1945', 'name': 'Berg en Dal', 'type': 'municipality'},
        {'id': 'GM1724', 'name': 'Bergeijk', 'type': 'municipality'},
        {'id': 'GM0373', 'name': 'Bergen (NH.)', 'type': 'municipality'},
        {'id': 'GM0893', 'name': 'Bergen (L.)', 'type': 'municipality'},
        {'id': 'GM0748', 'name': 'Bergen op Zoom', 'type': 'municipality'},
        {'id': 'GM1859', 'name': 'Berkelland', 'type': 'municipality'},
        {'id': 'GM1721', 'name': 'Bernheze', 'type': 'municipality'},
        {'id': 'GM0753', 'name': 'Best', 'type': 'municipality'},
        {'id': 'GM0209', 'name': 'Beuningen', 'type': 'municipality'},
        {'id': 'GM0375', 'name': 'Beverwijk', 'type': 'municipality'},
        {'id': 'GM0310', 'name': 'De Bilt', 'type': 'municipality'},
        {'id': 'GM1728', 'name': 'Bladel', 'type': 'municipality'},
        {'id': 'GM0376', 'name': 'Blaricum', 'type': 'municipality'},
        {'id': 'GM0377', 'name': 'Bloemendaal', 'type': 'municipality'},
        {'id': 'GM1901', 'name': 'Bodegraven-Reeuwijk', 'type': 'municipality'},
        {'id': 'GM0755', 'name': 'Boekel', 'type': 'municipality'},
        {'id': 'GM1681', 'name': 'Borger-Odoorn', 'type': 'municipality'},
        {'id': 'GM0147', 'name': 'Borne', 'type': 'municipality'},
        {'id': 'GM0654', 'name': 'Borsele', 'type': 'municipality'},
        {'id': 'GM0757', 'name': 'Boxtel', 'type': 'municipality'},
        {'id': 'GM0758', 'name': 'Breda', 'type': 'municipality'},
        {'id': 'GM1876', 'name': 'Bronckhorst', 'type': 'municipality'},
        {'id': 'GM0213', 'name': 'Brummen', 'type': 'municipality'},
        {'id': 'GM0899', 'name': 'Brunssum', 'type': 'municipality'},
        {'id': 'GM0312', 'name': 'Bunnik', 'type': 'municipality'},
        {'id': 'GM0313', 'name': 'Bunschoten', 'type': 'municipality'},
        {'id': 'GM0214', 'name': 'Buren', 'type': 'municipality'},
        {'id': 'GM0502', 'name': 'Capelle aan den IJssel', 'type': 'municipality'},
        {'id': 'GM0383', 'name': 'Castricum', 'type': 'municipality'},
        {'id': 'GM1706', 'name': 'Cranendonck', 'type': 'municipality'},
        {'id': 'GM0216', 'name': 'Culemborg', 'type': 'municipality'},
        {'id': 'GM0148', 'name': 'Dalfsen', 'type': 'municipality'},
        {'id': 'GM1891', 'name': 'Dantumadiel', 'type': 'municipality'},
        {'id': 'GM0503', 'name': 'Delft', 'type': 'municipality'},
        {'id': 'GM0400', 'name': 'Den Helder', 'type': 'municipality'},
        {'id': 'GM0762', 'name': 'Deurne', 'type': 'municipality'},
        {'id': 'GM0150', 'name': 'Deventer', 'type': 'municipality'},
        {'id': 'GM0384', 'name': 'Diemen', 'type': 'municipality'},
        {'id': 'GM1774', 'name': 'Dinkelland', 'type': 'municipality'},
        {'id': 'GM0221', 'name': 'Doesburg', 'type': 'municipality'},
        {'id': 'GM0222', 'name': 'Doetinchem', 'type': 'municipality'},
        {'id': 'GM0766', 'name': 'Dongen', 'type': 'municipality'},
        {'id': 'GM0505', 'name': 'Dordrecht', 'type': 'municipality'},
        {'id': 'GM0498', 'name': 'Drechterland', 'type': 'municipality'},
        {'id': 'GM1719', 'name': 'Drimmelen', 'type': 'municipality'},
        {'id': 'GM0303', 'name': 'Dronten', 'type': 'municipality'},
        {'id': 'GM0225', 'name': 'Druten', 'type': 'municipality'},
        {'id': 'GM0226', 'name': 'Duiven', 'type': 'municipality'},
        {'id': 'GM1711', 'name': 'Echt-Susteren', 'type': 'municipality'},
        {'id': 'GM0385', 'name': 'Edam-Volendam', 'type': 'municipality'},
        {'id': 'GM0228', 'name': 'Ede', 'type': 'municipality'},
        {'id': 'GM0770', 'name': 'Eersel', 'type': 'municipality'},
        {'id': 'GM0317', 'name': 'Eemnes', 'type': 'municipality'},
        {'id': 'GM1979', 'name': 'Eemsdelta', 'type': 'municipality'},
        {'id': 'GM1903', 'name': 'Eijsden-Margraten', 'type': 'municipality'},
        {'id': 'GM0772', 'name': 'Eindhoven', 'type': 'municipality'},
        {'id': 'GM0230', 'name': 'Elburg', 'type': 'municipality'},
        {'id': 'GM0114', 'name': 'Emmen', 'type': 'municipality'},
        {'id': 'GM0388', 'name': 'Enkhuizen', 'type': 'municipality'},
        {'id': 'GM0153', 'name': 'Enschede', 'type': 'municipality'},
        {'id': 'GM0232', 'name': 'Epe', 'type': 'municipality'},
        {'id': 'GM0233', 'name': 'Ermelo', 'type': 'municipality'},
        {'id': 'GM0777', 'name': 'Etten-Leur', 'type': 'municipality'},
        {'id': 'GM1940', 'name': 'De Fryske Marren', 'type': 'municipality'},
        {'id': 'GM0779', 'name': 'Geertruidenberg', 'type': 'municipality'},
        {'id': 'GM1771', 'name': 'Geldrop-Mierlo', 'type': 'municipality'},
        {'id': 'GM1652', 'name': 'Gemert-Bakel', 'type': 'municipality'},
        {'id': 'GM0907', 'name': 'Gennep', 'type': 'municipality'},
        {'id': 'GM0784', 'name': 'Gilze en Rijen', 'type': 'municipality'},
        {'id': 'GM0664', 'name': 'Goes', 'type': 'municipality'},
        {'id': 'GM0785', 'name': 'Goirle', 'type': 'municipality'},
        {'id': 'GM1942', 'name': 'Gooise Meren', 'type': 'municipality'},
        {'id': 'GM0512', 'name': 'Gorinchem', 'type': 'municipality'},
        {'id': 'GM0513', 'name': 'Gouda', 'type': 'municipality'},
        {'id': 'GM0518', 'name': "'s-Gravenhage"},
        {'id': 'GM0158', 'name': 'Haaksbergen', 'type': 'municipality'},
        {'id': 'GM0392', 'name': 'Haarlem', 'type': 'municipality'},
        {'id': 'GM0394', 'name': 'Haarlemmermeer', 'type': 'municipality'},
        {'id': 'GM1655', 'name': 'Halderberge', 'type': 'municipality'},
        {'id': 'GM0160', 'name': 'Hardenberg', 'type': 'municipality'},
        {'id': 'GM0243', 'name': 'Harderwijk', 'type': 'municipality'},
        {'id': 'GM0523', 'name': 'Hardinxveld-Giessendam', 'type': 'municipality'},
        {'id': 'GM0072', 'name': 'Harlingen', 'type': 'municipality'},
        {'id': 'GM0244', 'name': 'Hattem', 'type': 'municipality'},
        {'id': 'GM0396', 'name': 'Heemskerk', 'type': 'municipality'},
        {'id': 'GM0397', 'name': 'Heemstede', 'type': 'municipality'},
        {'id': 'GM1658', 'name': 'Heeze-Leende', 'type': 'municipality'},
        {'id': 'GM0246', 'name': 'Heerde', 'type': 'municipality'},
        {'id': 'GM0074', 'name': 'Heerenveen', 'type': 'municipality'},
        {'id': 'GM0917', 'name': 'Heerlen', 'type': 'municipality'},
        {'id': 'GM0399', 'name': 'Heiloo', 'type': 'municipality'},
        {'id': 'GM0163', 'name': 'Hellendoorn', 'type': 'municipality'},
        {'id': 'GM0164', 'name': 'Hengelo', 'type': 'municipality'},
        {'id': 'GM0531', 'name': 'Hendrik-Ido-Ambacht', 'type': 'municipality'},
        {'id': 'GM1966', 'name': 'Het Hogeland', 'type': 'municipality'},
        {'id': 'GM0252', 'name': 'Heumen', 'type': 'municipality'},
        {'id': 'GM0797', 'name': 'Heusden', 'type': 'municipality'},
        {'id': 'GM0534', 'name': 'Hillegom', 'type': 'municipality'},
        {'id': 'GM0798', 'name': 'Hilvarenbeek', 'type': 'municipality'},
        {'id': 'GM0402', 'name': 'Hilversum', 'type': 'municipality'},
        {'id': 'GM1735', 'name': 'Hof van Twente', 'type': 'municipality'},
        {'id': 'GM1963', 'name': 'Hoeksche Waard', 'type': 'municipality'},
        {'id': 'GM0118', 'name': 'Hoogeveen', 'type': 'municipality'},
        {'id': 'GM0405', 'name': 'Hoorn', 'type': 'municipality'},
        {'id': 'GM1507', 'name': 'Horst aan de Maas', 'type': 'municipality'},
        {'id': 'GM0321', 'name': 'Houten', 'type': 'municipality'},
        {'id': 'GM0406', 'name': 'Huizen', 'type': 'municipality'},
        {'id': 'GM0677', 'name': 'Hulst', 'type': 'municipality'},
        {'id': 'GM0353', 'name': 'IJsselstein', 'type': 'municipality'},
        {'id': 'GM0166', 'name': 'Kampen', 'type': 'municipality'},
        {'id': 'GM0678', 'name': 'Kapelle', 'type': 'municipality'},
        {'id': 'GM0537', 'name': 'Katwijk', 'type': 'municipality'},
        {'id': 'GM0928', 'name': 'Kerkrade', 'type': 'municipality'},
        {'id': 'GM1598', 'name': 'Koggenland', 'type': 'municipality'},
        {'id': 'GM0542', 'name': 'Krimpen aan den IJssel', 'type': 'municipality'},
        {'id': 'GM1931', 'name': 'Krimpenerwaard', 'type': 'municipality'},
        {'id': 'GM1659', 'name': 'Laarbeek', 'type': 'municipality'},
        {'id': 'GM1982', 'name': 'Land van Cuijk', 'type': 'municipality'},
        {'id': 'GM0415', 'name': 'Landsmeer', 'type': 'municipality'},
        {'id': 'GM0882', 'name': 'Landgraaf', 'type': 'municipality'},
        {'id': 'GM0417', 'name': 'Laren', 'type': 'municipality'},
        {'id': 'GM0080', 'name': 'Leeuwarden', 'type': 'municipality'},
        {'id': 'GM0546', 'name': 'Leiden', 'type': 'municipality'},
        {'id': 'GM0547', 'name': 'Leiderdorp', 'type': 'municipality'},
        {'id': 'GM1916', 'name': 'Leidschendam-Voorburg', 'type': 'municipality'},
        {'id': 'GM0995', 'name': 'Lelystad', 'type': 'municipality'},
        {'id': 'GM0327', 'name': 'Leusden', 'type': 'municipality'},
        {'id': 'GM1640', 'name': 'Leudal', 'type': 'municipality'},
        {'id': 'GM1705', 'name': 'Lingewaard', 'type': 'municipality'},
        {'id': 'GM0553', 'name': 'Lisse', 'type': 'municipality'},
        {'id': 'GM0262', 'name': 'Lochem', 'type': 'municipality'},
        {'id': 'GM0809', 'name': 'Loon op Zand', 'type': 'municipality'},
        {'id': 'GM0331', 'name': 'Lopik', 'type': 'municipality'},
        {'id': 'GM0168', 'name': 'Losser', 'type': 'municipality'},
        {'id': 'GM0263', 'name': 'Maasdriel', 'type': 'municipality'},
        {'id': 'GM1641', 'name': 'Maasgouw', 'type': 'municipality'},
        {'id': 'GM1991', 'name': 'Maashorst', 'type': 'municipality'},
        {'id': 'GM0556', 'name': 'Maassluis', 'type': 'municipality'},
        {'id': 'GM0935', 'name': 'Maastricht', 'type': 'municipality'},
        {'id': 'GM0420', 'name': 'Medemblik', 'type': 'municipality'},
        {'id': 'GM0938', 'name': 'Meerssen', 'type': 'municipality'},
        {'id': 'GM1948', 'name': 'Meierijstad', 'type': 'municipality'},
        {'id': 'GM0119', 'name': 'Meppel', 'type': 'municipality'},
        {'id': 'GM0687', 'name': 'Middelburg', 'type': 'municipality'},
        {'id': 'GM1952', 'name': 'Midden-Groningen', 'type': 'municipality'},
        {'id': 'GM1842', 'name': 'Midden-Delfland', 'type': 'municipality'},
        {'id': 'GM1731', 'name': 'Midden-Drenthe', 'type': 'municipality'},
        {'id': 'GM1709', 'name': 'Moerdijk', 'type': 'municipality'},
        {'id': 'GM1978', 'name': 'Molenlanden', 'type': 'municipality'},
        {'id': 'GM0335', 'name': 'Montfoort', 'type': 'municipality'},
        {'id': 'GM1955', 'name': 'Montferland', 'type': 'municipality'},
        {'id': 'GM0944', 'name': 'Mook en Middelaar', 'type': 'municipality'},
        {'id': 'GM1740', 'name': 'Neder-Betuwe', 'type': 'municipality'},
        {'id': 'GM0946', 'name': 'Nederweert', 'type': 'municipality'},
        {'id': 'GM0356', 'name': 'Nieuwegein', 'type': 'municipality'},
        {'id': 'GM0569', 'name': 'Nieuwkoop', 'type': 'municipality'},
        {'id': 'GM1930', 'name': 'Nissewaard', 'type': 'municipality'},
        {'id': 'GM1970', 'name': 'Noardeast-Fryslân', 'type': 'municipality'},
        {'id': 'GM1695', 'name': 'Noord-Beveland', 'type': 'municipality'},
        {'id': 'GM0171', 'name': 'Noordoostpolder', 'type': 'municipality'},
        {'id': 'GM1699', 'name': 'Noordenveld', 'type': 'municipality'},
        {'id': 'GM0575', 'name': 'Noordwijk', 'type': 'municipality'},
        {'id': 'GM0820', 'name': 'Nuenen, Gerwen en Nederwetten', 'type': 'municipality'},
        {'id': 'GM0302', 'name': 'Nunspeet', 'type': 'municipality'},
        {'id': 'GM0579', 'name': 'Oegstgeest', 'type': 'municipality'},
        {'id': 'GM0823', 'name': 'Oirschot', 'type': 'municipality'},
        {'id': 'GM0824', 'name': 'Oisterwijk', 'type': 'municipality'},
        {'id': 'GM1895', 'name': 'Oldambt', 'type': 'municipality'},
        {'id': 'GM0173', 'name': 'Oldenzaal', 'type': 'municipality'},
        {'id': 'GM1773', 'name': 'Olst-Wijhe', 'type': 'municipality'},
        {'id': 'GM0175', 'name': 'Ommen', 'type': 'municipality'},
        {'id': 'GM1586', 'name': 'Oost Gelre', 'type': 'municipality'},
        {'id': 'GM0826', 'name': 'Oosterhout', 'type': 'municipality'},
        {'id': 'GM0085', 'name': 'Ooststellingwerf', 'type': 'municipality'},
        {'id': 'GM0431', 'name': 'Oostzaan', 'type': 'municipality'},
        {'id': 'GM0432', 'name': 'Opmeer', 'type': 'municipality'},
        {'id': 'GM0086', 'name': 'Opsterland', 'type': 'municipality'},
        {'id': 'GM0828', 'name': 'Oss', 'type': 'municipality'},
        {'id': 'GM0437', 'name': 'Ouder-Amstel', 'type': 'municipality'},
        {'id': 'GM0589', 'name': 'Oudewater', 'type': 'municipality'},
        {'id': 'GM1509', 'name': 'Oude IJsselstreek', 'type': 'municipality'},
        {'id': 'GM0590', 'name': 'Papendrecht', 'type': 'municipality'},
        {'id': 'GM1894', 'name': 'Peel en Maas', 'type': 'municipality'},
        {'id': 'GM0765', 'name': 'Pekela', 'type': 'municipality'},
        {'id': 'GM1926', 'name': 'Pijnacker-Nootdorp', 'type': 'municipality'},
        {'id': 'PV21', 'name': 'Provincie Friesland', 'type': 'province'},
        {'id': 'PV22', 'name': 'Provincie Drenthe', 'type': 'province'},
        {'id': 'PV23', 'name': 'Provincie Overijssel', 'type': 'province'},
        {'id': 'PV25', 'name': 'Provincie Gelderland', 'type': 'province'},
        {'id': 'PV26', 'name': 'Provincie Utrecht', 'type': 'province'},
        {'id': 'PV27', 'name': 'Provincie Noord-Holland', 'type': 'province'},
        {'id': 'PV28', 'name': 'Provincie Zuid-Holland', 'type': 'province'},
        {'id': 'PV29', 'name': 'Provincie Zeeland', 'type': 'province'},
        {'id': 'PV30', 'name': 'Provincie Noord-Brabant', 'type': 'province'},
        {'id': 'PV31', 'name': 'Provincie Limburg', 'type': 'province'},
        {'id': 'GM0439', 'name': 'Purmerend', 'type': 'municipality'},
        {'id': 'GM0273', 'name': 'Putten', 'type': 'municipality'},
        {'id': 'GM0177', 'name': 'Raalte', 'type': 'municipality'},
        {'id': 'GM0703', 'name': 'Reimerswaal', 'type': 'municipality'},
        {'id': 'GM0274', 'name': 'Renkum', 'type': 'municipality'},
        {'id': 'GM0339', 'name': 'Renswoude', 'type': 'municipality'},
        {'id': 'GM1667', 'name': 'Reusel-De Mierden', 'type': 'municipality'},
        {'id': 'GM0275', 'name': 'Rheden', 'type': 'municipality'},
        {'id': 'GM0340', 'name': 'Rhenen', 'type': 'municipality'},
        {'id': 'GM0597', 'name': 'Ridderkerk', 'type': 'municipality'},
        {'id': 'GM1742', 'name': 'Rijssen-Holten', 'type': 'municipality'},
        {'id': 'GM0603', 'name': 'Rijswijk', 'type': 'municipality'},
        {'id': 'GM0957', 'name': 'Roermond', 'type': 'municipality'},
        {'id': 'GM1669', 'name': 'Roerdalen', 'type': 'municipality'},
        {'id': 'GM1674', 'name': 'Roosendaal', 'type': 'municipality'},
        {'id': 'GM0599', 'name': 'Rotterdam', 'type': 'municipality'},
        {'id': 'GM0277', 'name': 'Rozendaal', 'type': 'municipality'},
        {'id': 'GM0840', 'name': 'Rucphen', 'type': 'municipality'},
        {'id': 'GM0441', 'name': 'Schagen', 'type': 'municipality'},
        {'id': 'GM0279', 'name': 'Scherpenzeel', 'type': 'municipality'},
        {'id': 'GM0606', 'name': 'Schiedam', 'type': 'municipality'},
        {'id': 'GM0088', 'name': 'Schiermonnikoog', 'type': 'municipality'},
        {'id': 'GM1676', 'name': 'Schouwen-Duiveland', 'type': 'municipality'},
        {'id': 'GM0965', 'name': 'Simpelveld', 'type': 'municipality'},
        {'id': 'GM1883', 'name': 'Sittard-Geleen', 'type': 'municipality'},
        {'id': 'GM0610', 'name': 'Sliedrecht', 'type': 'municipality'},
        {'id': 'GM1714', 'name': 'Sluis', 'type': 'municipality'},
        {'id': 'GM0090', 'name': 'Smallingerland', 'type': 'municipality'},
        {'id': 'GM0342', 'name': 'Soest', 'type': 'municipality'},
        {'id': 'GM0847', 'name': 'Someren', 'type': 'municipality'},
        {'id': 'GM0848', 'name': 'Son en Breugel', 'type': 'municipality'},
        {'id': 'GM0037', 'name': 'Stadskanaal', 'type': 'municipality'},
        {'id': 'GM0532', 'name': 'Stede Broec', 'type': 'municipality'},
        {'id': 'GM0851', 'name': 'Steenbergen', 'type': 'municipality'},
        {'id': 'GM1708', 'name': 'Steenwijkerland', 'type': 'municipality'},
        {'id': 'GM0971', 'name': 'Stein', 'type': 'municipality'},
        {'id': 'GM1904', 'name': 'Stichtse Vecht', 'type': 'municipality'},
        {'id': 'GM0715', 'name': 'Terneuzen', 'type': 'municipality'},
        {'id': 'GM0093', 'name': 'Terschelling', 'type': 'municipality'},
        {'id': 'GM0448', 'name': 'Texel', 'type': 'municipality'},
        {'id': 'GM1525', 'name': 'Teylingen', 'type': 'municipality'},
        {'id': 'GM0716', 'name': 'Tholen', 'type': 'municipality'},
        {'id': 'GM0281', 'name': 'Tiel', 'type': 'municipality'},
        {'id': 'GM0855', 'name': 'Tilburg', 'type': 'municipality'},
        {'id': 'GM0183', 'name': 'Tubbergen', 'type': 'municipality'},
        {'id': 'GM1700', 'name': 'Twenterand', 'type': 'municipality'},
        {'id': 'GM1730', 'name': 'Tynaarlo', 'type': 'municipality'},
        {'id': 'GM0737', 'name': 'Tytsjerksteradiel', 'type': 'municipality'},
        {'id': 'GM0450', 'name': 'Uitgeest', 'type': 'municipality'},
        {'id': 'GM0451', 'name': 'Uithoorn', 'type': 'municipality'},
        {'id': 'GM0184', 'name': 'Urk', 'type': 'municipality'},
        {'id': 'GM0344', 'name': 'Utrecht', 'type': 'municipality'},
        {'id': 'GM1581', 'name': 'Utrechtse Heuvelrug', 'type': 'municipality'},
        {'id': 'GM0981', 'name': 'Vaals', 'type': 'municipality'},
        {'id': 'GM0994', 'name': 'Valkenburg aan de Geul', 'type': 'municipality'},
        {'id': 'GM0858', 'name': 'Valkenswaard', 'type': 'municipality'},
        {'id': 'GM0047', 'name': 'Veendam', 'type': 'municipality'},
        {'id': 'GM0345', 'name': 'Veenendaal', 'type': 'municipality'},
        {'id': 'GM0717', 'name': 'Veere', 'type': 'municipality'},
        {'id': 'GM0861', 'name': 'Veldhoven', 'type': 'municipality'},
        {'id': 'GM0453', 'name': 'Velsen', 'type': 'municipality'},
        {'id': 'GM0983', 'name': 'Venlo', 'type': 'municipality'},
        {'id': 'GM0984', 'name': 'Venray', 'type': 'municipality'},
        {'id': 'GM1961', 'name': 'Vijfheerenlanden', 'type': 'municipality'},
        {'id': 'GM0622', 'name': 'Vlaardingen', 'type': 'municipality'},
        {'id': 'GM0096', 'name': 'Vlieland', 'type': 'municipality'},
        {'id': 'GM0718', 'name': 'Vlissingen', 'type': 'municipality'},
        {'id': 'GM0986', 'name': 'Voerendaal', 'type': 'municipality'},
        {'id': 'GM1992', 'name': 'Voorne aan Zee', 'type': 'municipality'},
        {'id': 'GM0626', 'name': 'Voorschoten', 'type': 'municipality'},
        {'id': 'GM0285', 'name': 'Voorst', 'type': 'municipality'},
        {'id': 'GM0865', 'name': 'Vught', 'type': 'municipality'},
        {'id': 'GM1949', 'name': 'Waadhoeke', 'type': 'municipality'},
        {'id': 'GM0866', 'name': 'Waalre', 'type': 'municipality'},
        {'id': 'GM0867', 'name': 'Waalwijk', 'type': 'municipality'},
        {'id': 'GM0627', 'name': 'Waddinxveen', 'type': 'municipality'},
        {'id': 'GM0289', 'name': 'Wageningen', 'type': 'municipality'},
        {'id': 'GM0629', 'name': 'Wassenaar', 'type': 'municipality'},
        {'id': 'GM0852', 'name': 'Waterland', 'type': 'municipality'},
        {'id': 'GM0988', 'name': 'Weert', 'type': 'municipality'},
        {'id': 'GM1960', 'name': 'West Betuwe', 'type': 'municipality'},
        {'id': 'GM0668', 'name': 'West Maas en Waal', 'type': 'municipality'},
        {'id': 'GM1969', 'name': 'Westerkwartier', 'type': 'municipality'},
        {'id': 'GM1950', 'name': 'Westerwolde', 'type': 'municipality'},
        {'id': 'GM1701', 'name': 'Westerveld', 'type': 'municipality'},
        {'id': 'GM0293', 'name': 'Westervoort', 'type': 'municipality'},
        {'id': 'GM1783', 'name': 'Westland', 'type': 'municipality'},
        {'id': 'GM0098', 'name': 'Weststellingwerf', 'type': 'municipality'},
        {'id': 'GM0189', 'name': 'Wierden', 'type': 'municipality'},
        {'id': 'GM0296', 'name': 'Wijchen', 'type': 'municipality'},
        {'id': 'GM0352', 'name': 'Wijk bij Duurstede', 'type': 'municipality'},
        {'id': 'GM1696', 'name': 'Wijdemeren', 'type': 'municipality'},
        {'id': 'GM0294', 'name': 'Winterswijk', 'type': 'municipality'},
        {'id': 'GM0873', 'name': 'Woensdrecht', 'type': 'municipality'},
        {'id': 'GM0632', 'name': 'Woerden', 'type': 'municipality'},
        {'id': 'GM0880', 'name': 'Wormerland', 'type': 'municipality'},
        {'id': 'GM0351', 'name': 'Woudenberg', 'type': 'municipality'},
        {'id': 'GM0479', 'name': 'Zaanstad', 'type': 'municipality'},
        {'id': 'GM0297', 'name': 'Zaltbommel', 'type': 'municipality'},
        {'id': 'GM0473', 'name': 'Zandvoort', 'type': 'municipality'},
        {'id': 'GM0050', 'name': 'Zeewolde', 'type': 'municipality'},
        {'id': 'GM0355', 'name': 'Zeist', 'type': 'municipality'},
        {'id': 'GM0299', 'name': 'Zevenaar', 'type': 'municipality'},
        {'id': 'GM0637', 'name': 'Zoetermeer', 'type': 'municipality'},
        {'id': 'GM0638', 'name': 'Zoeterwoude', 'type': 'municipality'},
        {'id': 'GM1892', 'name': 'Zuidplas', 'type': 'municipality'},
        {'id': 'GM0879', 'name': 'Zundert', 'type': 'municipality'},
        {'id': 'GM0301', 'name': 'Zutphen', 'type': 'municipality'},
        {'id': 'GM0193', 'name': 'Zwolle', 'type': 'municipality'},
        {'id': 'GM0642', 'name': 'Zwijndrecht', 'type': 'municipality'},
    ]
    