log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'

  mysql:
    address: ':3306'

  qdrant:
    address: ':6333'

  portainer:
    address: ':9000'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'info@linksmith.nl'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    frontend-router:
      rule: 'Host(`chat.bron.live`)'
      entryPoints:
        - web-secure
      service: frontend
      tls:
        certResolver: letsencrypt

    backend-router:
      rule: 'Host(`api.chat.bron.live`)'
      entryPoints:
        - web-secure
      service: backend
      tls:
        certResolver: letsencrypt

  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://frontend:3000

    backend:
      loadBalancer:
        servers:
          - url: http://backend:8000

    mysql:
      loadBalancer:
        servers:
          - url: http://mysql:3306

    qdrant:
      loadBalancer:
        servers:
          - url: http://qdrant:6333

    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000

providers:
  file:
    filename: /etc/traefik/traefik.stag.yml
    watch: true
